// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 10.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace OperationABS.Operation
{
    using System;
    using System.IO;
    using System.Xml;
    using System.Xml.Serialization;
    using System.Diagnostics;
    using System.Linq;
    using System.Xml.Linq;
    using System.Collections;
    using System.Collections.Generic;
    
    
    #line 1 "C:\GitHub\kallex\private\Demos\CQRS_CustomerBankAccountDemo\Abstractions\OperationABS\Operation\CSharpCode_v1_0.tt"
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "10.0.0.0")]
    public partial class CSharpCode_v1_0 : CSharpCode_v1_0Base
    {
        public virtual string TransformText()
        {
            this.Write(" \r\n");
            
            #line 18 "C:\GitHub\kallex\private\Demos\CQRS_CustomerBankAccountDemo\Abstractions\OperationABS\Operation\CSharpCode_v1_0.tt"
   
	string directoryName = GetContentDirectoryFromTemplateFullPath(Host.TemplateFile, IsLocal == false);
	
	string[] xmlFileNames = Directory.GetFiles(directoryName, "*.xml");

	
            
            #line default
            #line hidden
            this.Write("using System;\r\n\r\n\t");
            
            #line 26 "C:\GitHub\kallex\private\Demos\CQRS_CustomerBankAccountDemo\Abstractions\OperationABS\Operation\CSharpCode_v1_0.tt"

	
	foreach(string xmlFileName in xmlFileNames)
	{
		Operation_v1_0.OperationAbstractionType abstraction = LoadXml<Operation_v1_0.OperationAbstractionType>(xmlFileName);
		Operation_v1_0.OperationsType operations = abstraction.Operations;
		BeginNamespace(operations.codeNamespace);
		foreach(var operation in operations.Operation)
			GenerateOperation(operation);
		EndBlock();
		//PowerPointAddIn_v1_0.PowerPointAddInAbstraction abstraction = LoadXml<PowerPointAddIn_v1_0.PowerPointAddInAbstraction>(xmlFileName);
		//GenerateAddInBase(abstraction);
	}

            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
        private global::Microsoft.VisualStudio.TextTemplating.ITextTemplatingEngineHost hostValue;
        public virtual global::Microsoft.VisualStudio.TextTemplating.ITextTemplatingEngineHost Host
        {
            get
            {
                return this.hostValue;
            }
            set
            {
                this.hostValue = value;
            }
        }
        
        #line 40 "C:\GitHub\kallex\private\Demos\CQRS_CustomerBankAccountDemo\Abstractions\OperationABS\Operation\CSharpCode_v1_0.tt"
 
	#region Class Level Variable Block
	
	//CQRS_v1_0.DomainType CurrentDomain;
	
	public static void MyGenerate()
	{
		new OperationABS.Operation.
			CSharpCode_v1_0().	TransformText();
	}
	
	
	void GenerateOperation(Operation_v1_0.OperationType operation)
	{
		string operationName = operation.name;
		string parameterClassName = operationName + "Parameters";
		string resultClassName = operationName + "Results";
		if(operation.Parameters != null)
			GenerateVariableClassDefinition(parameterClassName, operation.Parameters.Parameter);
		
        
        #line default
        #line hidden
        
        #line 59 "C:\GitHub\kallex\private\Demos\CQRS_CustomerBankAccountDemo\Abstractions\OperationABS\Operation\CSharpCode_v1_0.tt"
this.Write("\r\n\t\tpublic class ");

        
        #line default
        #line hidden
        
        #line 61 "C:\GitHub\kallex\private\Demos\CQRS_CustomerBankAccountDemo\Abstractions\OperationABS\Operation\CSharpCode_v1_0.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(operationName));

        
        #line default
        #line hidden
        
        #line 61 "C:\GitHub\kallex\private\Demos\CQRS_CustomerBankAccountDemo\Abstractions\OperationABS\Operation\CSharpCode_v1_0.tt"
this.Write(" \r\n\t\t{\r\n\t\t");

        
        #line default
        #line hidden
        
        #line 63 "C:\GitHub\kallex\private\Demos\CQRS_CustomerBankAccountDemo\Abstractions\OperationABS\Operation\CSharpCode_v1_0.tt"


		GenerateParameterPreparation(parameterClassName, operation.Parameters);
		//GenerateInternalReturnValueClasses(operation.Execution.SequentialExecution);
		GenerateExecution(operation);
		
		
        
        #line default
        #line hidden
        
        #line 69 "C:\GitHub\kallex\private\Demos\CQRS_CustomerBankAccountDemo\Abstractions\OperationABS\Operation\CSharpCode_v1_0.tt"
this.Write("\t\t}\r\n\t\t");

        
        #line default
        #line hidden
        
        #line 71 "C:\GitHub\kallex\private\Demos\CQRS_CustomerBankAccountDemo\Abstractions\OperationABS\Operation\CSharpCode_v1_0.tt"

		if(operation.OperationReturnValues != null)
			GenerateVariableClassDefinition(resultClassName, operation.OperationReturnValues.ReturnValue);

	}
	void GenerateInternalReturnValueClasses(object[] executionItems)
	{
		foreach(object executionItem in executionItems)
			GenerateReturnValueClassDefinition(executionItem);
	}
	
	void GenerateReturnValueClassDefinition(object executionItem)
	{
		Operation_v1_0.OperationExecuteType operationExec = executionItem as Operation_v1_0.OperationExecuteType;
		Operation_v1_0.MethodExecuteType methodExec = executionItem as Operation_v1_0.MethodExecuteType;
		Operation_v1_0.TargetDefinitionType targetDef = executionItem as Operation_v1_0.TargetDefinitionType;
		if(operationExec != null) {
		}
		else if(methodExec != null)
			GenerateReturnValueClassDefinition(methodExec.name, methodExec.ReturnValue, false);
		else if(targetDef != null) {
		} else
			throw new NotSupportedException("Execution item type: " + executionItem.GetType().Name);
	}
	
	
	string[] GetParameterArray(string prefix, Operation_v1_0.TargetType[] targets)
	{
		if(targets == null)
			return new string[0];
		string[] result = targets.Select(target => prefix + target.name).ToArray();
		return result;
	}
	
	string GetParametersAndTargetsAsAllParams(string paramPrefix, Operation_v1_0.TargetType[] parameters,
		Operation_v1_0.TargetType[] targets)
	{
		string[] parameterParameters = GetParameterArray(paramPrefix, parameters);
		string[] targetParameters = GetParameterArray("", targets);
		string allParameters = String.Join(", ", parameterParameters.Union(targetParameters).ToArray());
		return allParameters;
	}
	
	string GetReturnValueType(string returnValueOwner, Operation_v1_0.VariableType[] returnValues, bool isOperation)
	{
		if(returnValues == null)
			return "void";
		if(returnValues.Length == 1 && isOperation == false)
			return returnValues[0].dataType;
		return GetReturnValueClassName(returnValueOwner);
	}
	
	string GetReturnValueClassName(string returnValueOwner)
	{
		return returnValueOwner + "ReturnValue";
	}
	
	string GetExecutionOutputName(string returnValueOwner)
	{
		return returnValueOwner + "Output";
	}
	
	void GenerateReturnValueClassDefinition(string returnValueOwner, Operation_v1_0.VariableType[] returnValues, bool isOperation)
	{
		if(returnValues == null || (returnValues.Length < 2 && isOperation == false))
			return;
		string returnValueClassName = GetReturnValueClassName(returnValueOwner);
		GenerateVariableClassDefinition(returnValueClassName, returnValues);
	}
	
	void GenerateOperationExecuteItem(Operation_v1_0.OperationExecuteType operationExec)
	{
		
		
        
        #line default
        #line hidden
        
        #line 144 "C:\GitHub\kallex\private\Demos\CQRS_CustomerBankAccountDemo\Abstractions\OperationABS\Operation\CSharpCode_v1_0.tt"
this.Write("\t\t\r\n\t\t");

        
        #line default
        #line hidden
        
        #line 146 "C:\GitHub\kallex\private\Demos\CQRS_CustomerBankAccountDemo\Abstractions\OperationABS\Operation\CSharpCode_v1_0.tt"

	}
	
	void GenerateMethodExecuteItem(Operation_v1_0.MethodExecuteType methodExec)
	{
		string allParameters = GetParametersAndTargetsAsAllParams("parameters.",
			methodExec.Parameter, methodExec.Target);
		string returnValueType = GetReturnValueType(methodExec.name, methodExec.ReturnValue, false);
		string executionOutputName = GetExecutionOutputName(methodExec.name);
		string returnValueOutputString = methodExec.ReturnValue != null ? 
			returnValueType + " " + executionOutputName + " = " : "";
		
        
        #line default
        #line hidden
        
        #line 157 "C:\GitHub\kallex\private\Demos\CQRS_CustomerBankAccountDemo\Abstractions\OperationABS\Operation\CSharpCode_v1_0.tt"
this.Write("\t\t");

        
        #line default
        #line hidden
        
        #line 158 "C:\GitHub\kallex\private\Demos\CQRS_CustomerBankAccountDemo\Abstractions\OperationABS\Operation\CSharpCode_v1_0.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(returnValueOutputString));

        
        #line default
        #line hidden
        
        #line 158 "C:\GitHub\kallex\private\Demos\CQRS_CustomerBankAccountDemo\Abstractions\OperationABS\Operation\CSharpCode_v1_0.tt"
this.Write("ExecuteMethod_");

        
        #line default
        #line hidden
        
        #line 158 "C:\GitHub\kallex\private\Demos\CQRS_CustomerBankAccountDemo\Abstractions\OperationABS\Operation\CSharpCode_v1_0.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(methodExec.name));

        
        #line default
        #line hidden
        
        #line 158 "C:\GitHub\kallex\private\Demos\CQRS_CustomerBankAccountDemo\Abstractions\OperationABS\Operation\CSharpCode_v1_0.tt"
this.Write("(");

        
        #line default
        #line hidden
        
        #line 158 "C:\GitHub\kallex\private\Demos\CQRS_CustomerBankAccountDemo\Abstractions\OperationABS\Operation\CSharpCode_v1_0.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(allParameters));

        
        #line default
        #line hidden
        
        #line 158 "C:\GitHub\kallex\private\Demos\CQRS_CustomerBankAccountDemo\Abstractions\OperationABS\Operation\CSharpCode_v1_0.tt"
this.Write(");\t\t\r\n\t\t");

        
        #line default
        #line hidden
        
        #line 159 "C:\GitHub\kallex\private\Demos\CQRS_CustomerBankAccountDemo\Abstractions\OperationABS\Operation\CSharpCode_v1_0.tt"

	}
	
	void GenerateTargetDefinitionItem(Operation_v1_0.TargetDefinitionType targetDef)
	{
		string allParameters = GetParametersAndTargetsAsAllParams("parameters.",
			targetDef.Parameter, targetDef.Target);
		
        
        #line default
        #line hidden
        
        #line 166 "C:\GitHub\kallex\private\Demos\CQRS_CustomerBankAccountDemo\Abstractions\OperationABS\Operation\CSharpCode_v1_0.tt"
this.Write("\t\t");

        
        #line default
        #line hidden
        
        #line 167 "C:\GitHub\kallex\private\Demos\CQRS_CustomerBankAccountDemo\Abstractions\OperationABS\Operation\CSharpCode_v1_0.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(targetDef.dataType));

        
        #line default
        #line hidden
        
        #line 167 "C:\GitHub\kallex\private\Demos\CQRS_CustomerBankAccountDemo\Abstractions\OperationABS\Operation\CSharpCode_v1_0.tt"
this.Write(" ");

        
        #line default
        #line hidden
        
        #line 167 "C:\GitHub\kallex\private\Demos\CQRS_CustomerBankAccountDemo\Abstractions\OperationABS\Operation\CSharpCode_v1_0.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(targetDef.name));

        
        #line default
        #line hidden
        
        #line 167 "C:\GitHub\kallex\private\Demos\CQRS_CustomerBankAccountDemo\Abstractions\OperationABS\Operation\CSharpCode_v1_0.tt"
this.Write(" = GetTarget_");

        
        #line default
        #line hidden
        
        #line 167 "C:\GitHub\kallex\private\Demos\CQRS_CustomerBankAccountDemo\Abstractions\OperationABS\Operation\CSharpCode_v1_0.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(targetDef.name));

        
        #line default
        #line hidden
        
        #line 167 "C:\GitHub\kallex\private\Demos\CQRS_CustomerBankAccountDemo\Abstractions\OperationABS\Operation\CSharpCode_v1_0.tt"
this.Write("(");

        
        #line default
        #line hidden
        
        #line 167 "C:\GitHub\kallex\private\Demos\CQRS_CustomerBankAccountDemo\Abstractions\OperationABS\Operation\CSharpCode_v1_0.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(allParameters));

        
        #line default
        #line hidden
        
        #line 167 "C:\GitHub\kallex\private\Demos\CQRS_CustomerBankAccountDemo\Abstractions\OperationABS\Operation\CSharpCode_v1_0.tt"
this.Write(");\t\r\n\t\t");

        
        #line default
        #line hidden
        
        #line 168 "C:\GitHub\kallex\private\Demos\CQRS_CustomerBankAccountDemo\Abstractions\OperationABS\Operation\CSharpCode_v1_0.tt"

	}
	
	void GenerateExecutionItem(object executionItem)
	{
		Operation_v1_0.OperationExecuteType operationExec = executionItem as Operation_v1_0.OperationExecuteType;
		Operation_v1_0.MethodExecuteType methodExec = executionItem as Operation_v1_0.MethodExecuteType;
		Operation_v1_0.TargetDefinitionType targetDef = executionItem as Operation_v1_0.TargetDefinitionType;
		if(operationExec != null)
			GenerateOperationExecuteItem(operationExec);
		else if(methodExec != null)
			GenerateMethodExecuteItem(methodExec);
		else if(targetDef != null)
			GenerateTargetDefinitionItem(targetDef);
		else
			throw new NotSupportedException("Execution item type: " + executionItem.GetType().Name);
	}
	
	void GenerateExecution(Operation_v1_0.OperationType operation)
	{
		string operationName = operation.name;
		string parametersCallingString = operation.Parameters != null ?  operationName + "Parameters parameters" : "";
		string resultsTypeNameString = operation.OperationReturnValues != null ? operationName + "ReturnValue" : "void";
		string parameterPreparationCallString = operation.Parameters != null ? "PrepareParameters(parameters);" : ""; 
		
        
        #line default
        #line hidden
        
        #line 192 "C:\GitHub\kallex\private\Demos\CQRS_CustomerBankAccountDemo\Abstractions\OperationABS\Operation\CSharpCode_v1_0.tt"
this.Write("\t\tpublic static ");

        
        #line default
        #line hidden
        
        #line 193 "C:\GitHub\kallex\private\Demos\CQRS_CustomerBankAccountDemo\Abstractions\OperationABS\Operation\CSharpCode_v1_0.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(resultsTypeNameString));

        
        #line default
        #line hidden
        
        #line 193 "C:\GitHub\kallex\private\Demos\CQRS_CustomerBankAccountDemo\Abstractions\OperationABS\Operation\CSharpCode_v1_0.tt"
this.Write(" Execute(");

        
        #line default
        #line hidden
        
        #line 193 "C:\GitHub\kallex\private\Demos\CQRS_CustomerBankAccountDemo\Abstractions\OperationABS\Operation\CSharpCode_v1_0.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(parametersCallingString));

        
        #line default
        #line hidden
        
        #line 193 "C:\GitHub\kallex\private\Demos\CQRS_CustomerBankAccountDemo\Abstractions\OperationABS\Operation\CSharpCode_v1_0.tt"
this.Write(")\r\n\t\t{\r\n\t\t\t");

        
        #line default
        #line hidden
        
        #line 195 "C:\GitHub\kallex\private\Demos\CQRS_CustomerBankAccountDemo\Abstractions\OperationABS\Operation\CSharpCode_v1_0.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(parameterPreparationCallString));

        
        #line default
        #line hidden
        
        #line 195 "C:\GitHub\kallex\private\Demos\CQRS_CustomerBankAccountDemo\Abstractions\OperationABS\Operation\CSharpCode_v1_0.tt"
this.Write("\r\n\t\t\t");

        
        #line default
        #line hidden
        
        #line 196 "C:\GitHub\kallex\private\Demos\CQRS_CustomerBankAccountDemo\Abstractions\OperationABS\Operation\CSharpCode_v1_0.tt"

			//foreach(object executionItem in operation.Execution.SequentialExecution)
			//{
			//	GenerateExecutionItem(executionItem);
			//}
			
			
        
        #line default
        #line hidden
        
        #line 202 "C:\GitHub\kallex\private\Demos\CQRS_CustomerBankAccountDemo\Abstractions\OperationABS\Operation\CSharpCode_v1_0.tt"
this.Write("\t\t}\r\n\t\t");

        
        #line default
        #line hidden
        
        #line 204 "C:\GitHub\kallex\private\Demos\CQRS_CustomerBankAccountDemo\Abstractions\OperationABS\Operation\CSharpCode_v1_0.tt"

	}
	
	string GetCallingTargetsParameterString(Operation_v1_0.TargetType[] targets, string emptyParameterResult,
		string prefixText = "")
	{
		if(targets == null || targets.Length == 0)
			return emptyParameterResult;
		string[] targetNames = targets.Select(target => prefixText + target.name).ToArray();
		return String.Join(", ", targetNames);
	}
	
	void GenerateValidationItem(Operation_v1_0.ValidationType validationItem)
	{
		string validationMethodName = "ParameterValidation_" + validationItem.name + "_ThrowsException";
		string callingParametersString = GetCallingTargetsParameterString(validationItem.Target, "parameters", "parameters.");
		
        
        #line default
        #line hidden
        
        #line 220 "C:\GitHub\kallex\private\Demos\CQRS_CustomerBankAccountDemo\Abstractions\OperationABS\Operation\CSharpCode_v1_0.tt"
this.Write("\t\t");

        
        #line default
        #line hidden
        
        #line 221 "C:\GitHub\kallex\private\Demos\CQRS_CustomerBankAccountDemo\Abstractions\OperationABS\Operation\CSharpCode_v1_0.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(validationMethodName));

        
        #line default
        #line hidden
        
        #line 221 "C:\GitHub\kallex\private\Demos\CQRS_CustomerBankAccountDemo\Abstractions\OperationABS\Operation\CSharpCode_v1_0.tt"
this.Write("(");

        
        #line default
        #line hidden
        
        #line 221 "C:\GitHub\kallex\private\Demos\CQRS_CustomerBankAccountDemo\Abstractions\OperationABS\Operation\CSharpCode_v1_0.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(callingParametersString));

        
        #line default
        #line hidden
        
        #line 221 "C:\GitHub\kallex\private\Demos\CQRS_CustomerBankAccountDemo\Abstractions\OperationABS\Operation\CSharpCode_v1_0.tt"
this.Write(");\r\n\t\t");

        
        #line default
        #line hidden
        
        #line 222 "C:\GitHub\kallex\private\Demos\CQRS_CustomerBankAccountDemo\Abstractions\OperationABS\Operation\CSharpCode_v1_0.tt"

	}
	
	void GenerateModificationItem(Operation_v1_0.ModificationType modificationItem)
	{
		string modificationMethodName = "ParameterModification_" + modificationItem.name;
		string callingParametersString = GetCallingTargetsParameterString(modificationItem.Target, "parameters", "ref parameters.");
		
        
        #line default
        #line hidden
        
        #line 229 "C:\GitHub\kallex\private\Demos\CQRS_CustomerBankAccountDemo\Abstractions\OperationABS\Operation\CSharpCode_v1_0.tt"
this.Write("\t\t");

        
        #line default
        #line hidden
        
        #line 230 "C:\GitHub\kallex\private\Demos\CQRS_CustomerBankAccountDemo\Abstractions\OperationABS\Operation\CSharpCode_v1_0.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(modificationMethodName));

        
        #line default
        #line hidden
        
        #line 230 "C:\GitHub\kallex\private\Demos\CQRS_CustomerBankAccountDemo\Abstractions\OperationABS\Operation\CSharpCode_v1_0.tt"
this.Write("(");

        
        #line default
        #line hidden
        
        #line 230 "C:\GitHub\kallex\private\Demos\CQRS_CustomerBankAccountDemo\Abstractions\OperationABS\Operation\CSharpCode_v1_0.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(callingParametersString));

        
        #line default
        #line hidden
        
        #line 230 "C:\GitHub\kallex\private\Demos\CQRS_CustomerBankAccountDemo\Abstractions\OperationABS\Operation\CSharpCode_v1_0.tt"
this.Write(");\r\n\t\t");

        
        #line default
        #line hidden
        
        #line 231 "C:\GitHub\kallex\private\Demos\CQRS_CustomerBankAccountDemo\Abstractions\OperationABS\Operation\CSharpCode_v1_0.tt"

		
	}

	void GeneratePreparingItem(object preparingItem)
	{
		if(preparingItem == null)
			throw new ArgumentNullException("preparingItem");
		Operation_v1_0.ValidationType validationItem = preparingItem as Operation_v1_0.ValidationType;
		Operation_v1_0.ModificationType modificationItem = preparingItem as Operation_v1_0.ModificationType;
		if(validationItem != null)
			GenerateValidationItem(validationItem);
		else if(modificationItem != null)
			GenerateModificationItem(modificationItem);
		else 
			throw new NotSupportedException("Preparing item type: " + preparingItem.GetType().Name);
	}
	
	void GenerateParameterPreparation(string parameterClassName, Operation_v1_0.ParametersType parameters)
	{
		if(parameters == null)
			return;
		
        
        #line default
        #line hidden
        
        #line 253 "C:\GitHub\kallex\private\Demos\CQRS_CustomerBankAccountDemo\Abstractions\OperationABS\Operation\CSharpCode_v1_0.tt"
this.Write("\t\tprivate void PrepareParameters(");

        
        #line default
        #line hidden
        
        #line 254 "C:\GitHub\kallex\private\Demos\CQRS_CustomerBankAccountDemo\Abstractions\OperationABS\Operation\CSharpCode_v1_0.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(parameterClassName));

        
        #line default
        #line hidden
        
        #line 254 "C:\GitHub\kallex\private\Demos\CQRS_CustomerBankAccountDemo\Abstractions\OperationABS\Operation\CSharpCode_v1_0.tt"
this.Write(" parameters)\r\n\t\t{\r\n\t\t\t");

        
        #line default
        #line hidden
        
        #line 256 "C:\GitHub\kallex\private\Demos\CQRS_CustomerBankAccountDemo\Abstractions\OperationABS\Operation\CSharpCode_v1_0.tt"

			foreach(object preparingItem in parameters.Items)
				GeneratePreparingItem(preparingItem);
			
        
        #line default
        #line hidden
        
        #line 259 "C:\GitHub\kallex\private\Demos\CQRS_CustomerBankAccountDemo\Abstractions\OperationABS\Operation\CSharpCode_v1_0.tt"
this.Write("\t\t}\r\n\t\t");

        
        #line default
        #line hidden
        
        #line 261 "C:\GitHub\kallex\private\Demos\CQRS_CustomerBankAccountDemo\Abstractions\OperationABS\Operation\CSharpCode_v1_0.tt"

	}
	
	void GenerateVariableDefinition(Operation_v1_0.VariableType variableDef, string accessModifier, string initialAssignment)
	{
		GenerateVariableDefinition(variableDef.dataType, variableDef.name, accessModifier, initialAssignment);
	}
	
	void GenerateVariableDefinition(string dataType, string name, string accessModifier, string initialAssignment)
	{
		if(dataType == null)
			throw new ArgumentNullException("dataType");
		if(name == null)
			throw new ArgumentNullException("name");
		string accessString = accessModifier ?? "";
		string initialAssignmentString = initialAssignment != null ? " = " + initialAssignment : "";
		
        
        #line default
        #line hidden
        
        #line 277 "C:\GitHub\kallex\private\Demos\CQRS_CustomerBankAccountDemo\Abstractions\OperationABS\Operation\CSharpCode_v1_0.tt"
this.Write("\t\t");

        
        #line default
        #line hidden
        
        #line 278 "C:\GitHub\kallex\private\Demos\CQRS_CustomerBankAccountDemo\Abstractions\OperationABS\Operation\CSharpCode_v1_0.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(accessString));

        
        #line default
        #line hidden
        
        #line 278 "C:\GitHub\kallex\private\Demos\CQRS_CustomerBankAccountDemo\Abstractions\OperationABS\Operation\CSharpCode_v1_0.tt"
this.Write(" ");

        
        #line default
        #line hidden
        
        #line 278 "C:\GitHub\kallex\private\Demos\CQRS_CustomerBankAccountDemo\Abstractions\OperationABS\Operation\CSharpCode_v1_0.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(dataType));

        
        #line default
        #line hidden
        
        #line 278 "C:\GitHub\kallex\private\Demos\CQRS_CustomerBankAccountDemo\Abstractions\OperationABS\Operation\CSharpCode_v1_0.tt"
this.Write(" ");

        
        #line default
        #line hidden
        
        #line 278 "C:\GitHub\kallex\private\Demos\CQRS_CustomerBankAccountDemo\Abstractions\OperationABS\Operation\CSharpCode_v1_0.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(name));

        
        #line default
        #line hidden
        
        #line 278 "C:\GitHub\kallex\private\Demos\CQRS_CustomerBankAccountDemo\Abstractions\OperationABS\Operation\CSharpCode_v1_0.tt"
this.Write(" ");

        
        #line default
        #line hidden
        
        #line 278 "C:\GitHub\kallex\private\Demos\CQRS_CustomerBankAccountDemo\Abstractions\OperationABS\Operation\CSharpCode_v1_0.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(initialAssignmentString));

        
        #line default
        #line hidden
        
        #line 278 "C:\GitHub\kallex\private\Demos\CQRS_CustomerBankAccountDemo\Abstractions\OperationABS\Operation\CSharpCode_v1_0.tt"
this.Write(";\r\n\t\t");

        
        #line default
        #line hidden
        
        #line 279 "C:\GitHub\kallex\private\Demos\CQRS_CustomerBankAccountDemo\Abstractions\OperationABS\Operation\CSharpCode_v1_0.tt"

	}
	
	void GenerateVariableClassDefinition(string className, Operation_v1_0.VariableType[] variables)
	{
		if(className == null)
			throw new ArgumentNullException("className");
		if(variables == null)
			throw new ArgumentNullException("variables");
		
        
        #line default
        #line hidden
        
        #line 288 "C:\GitHub\kallex\private\Demos\CQRS_CustomerBankAccountDemo\Abstractions\OperationABS\Operation\CSharpCode_v1_0.tt"
this.Write("\t\tpublic class ");

        
        #line default
        #line hidden
        
        #line 289 "C:\GitHub\kallex\private\Demos\CQRS_CustomerBankAccountDemo\Abstractions\OperationABS\Operation\CSharpCode_v1_0.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(className));

        
        #line default
        #line hidden
        
        #line 289 "C:\GitHub\kallex\private\Demos\CQRS_CustomerBankAccountDemo\Abstractions\OperationABS\Operation\CSharpCode_v1_0.tt"
this.Write(" \r\n\t\t{\r\n\t\t");

        
        #line default
        #line hidden
        
        #line 291 "C:\GitHub\kallex\private\Demos\CQRS_CustomerBankAccountDemo\Abstractions\OperationABS\Operation\CSharpCode_v1_0.tt"

		foreach(var variable in variables)
			GenerateVariableDefinition(variable, "public", null);
		
        
        #line default
        #line hidden
        
        #line 294 "C:\GitHub\kallex\private\Demos\CQRS_CustomerBankAccountDemo\Abstractions\OperationABS\Operation\CSharpCode_v1_0.tt"
this.Write("\t\t}\r\n\t\t");

        
        #line default
        #line hidden
        
        #line 296 "C:\GitHub\kallex\private\Demos\CQRS_CustomerBankAccountDemo\Abstractions\OperationABS\Operation\CSharpCode_v1_0.tt"

	}
	
	void GenerateParameterDefinition(string operationName, Operation_v1_0.ParametersType parameters)
	{
		if(parameters == null || parameters.Parameter == null || parameters.Parameter.Length == 0)
			return;
		string parameterClassName = operationName + "Parameters";
		GenerateVariableClassDefinition(parameterClassName, parameters.Parameter);
	}
	
	#endregion

        
        #line default
        #line hidden
        
        #line 1 "C:\GitHub\kallex\private\Demos\CQRS_CustomerBankAccountDemo\Abstractions\OperationABS\Operation\..\..\abscommon\CommonInclude\Common\CommonCodeblocks.ttinclude"
 
	enum AbstractionShareLevel
	{
		Local,
		Shared,
		Modular,
	}
	
	AbstractionShareLevel ShareLevel = AbstractionShareLevel.Local;
	
	bool IsLocal
	{
		get {
			return ShareLevel == AbstractionShareLevel.Local;
		}
	}
	
	string GetContentDirectoryFromTemplateFullPath(string templateFullPath, bool isShared)
	{
		string templateDirectoryName = Path.GetDirectoryName(templateFullPath);
		string contentDir =  isShared ? @"In\Content_v1_0" : "Content_v1_0";
		string directoryName = Path.Combine(templateDirectoryName, contentDir);
		if(isShared) {
			System.IO.DirectoryInfo absRootDirInfo = new System.IO.DirectoryInfo(templateDirectoryName);
			absRootDirInfo = absRootDirInfo.Parent;
			string abstractionName = absRootDirInfo.Name;
			directoryName = directoryName.Replace(abstractionName, "AbstractionContent");
		}
		return directoryName;
	}
	
	void WriteContentToSingleOutput(string templateFullPath, string extension)
	{
		string templateDirectoryName = Path.GetDirectoryName(templateFullPath);
		string contentDir = "Out";
		string directoryName = Path.Combine(templateDirectoryName, contentDir);
		string contentFileName = System.IO.Path.GetFileNameWithoutExtension(templateFullPath) + extension;
		System.IO.DirectoryInfo absRootDirInfo = new System.IO.DirectoryInfo(templateDirectoryName);
		absRootDirInfo = absRootDirInfo.Parent;
		string abstractionName = absRootDirInfo.Name;
		directoryName = directoryName.Replace(abstractionName, "AbstractionContent");
		string contentFullName = Path.Combine(directoryName, contentFileName);
		string contentData = this.GenerationEnvironment.ToString();
		this.GenerationEnvironment.Clear();
		File.WriteAllText(contentFullName, contentData);
	}

	T LoadXml<T>(string xmlFileName) {
		using(FileStream fStream = File.OpenRead(xmlFileName)) {
			XmlSerializer serializer = new XmlSerializer(typeof(T));
			T result = (T) serializer.Deserialize(fStream);
			fStream.Close();
			return result;
		}
	}

	void BeginNamespace(string namespaceName) {
		
        
        #line default
        #line hidden
        
        #line 58 "C:\GitHub\kallex\private\Demos\CQRS_CustomerBankAccountDemo\Abstractions\OperationABS\Operation\..\..\abscommon\CommonInclude\Common\CommonCodeblocks.ttinclude"
this.Write("namespace ");

        
        #line default
        #line hidden
        
        #line 58 "C:\GitHub\kallex\private\Demos\CQRS_CustomerBankAccountDemo\Abstractions\OperationABS\Operation\..\..\abscommon\CommonInclude\Common\CommonCodeblocks.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(namespaceName));

        
        #line default
        #line hidden
        
        #line 58 "C:\GitHub\kallex\private\Demos\CQRS_CustomerBankAccountDemo\Abstractions\OperationABS\Operation\..\..\abscommon\CommonInclude\Common\CommonCodeblocks.ttinclude"
this.Write(" { \r\n\t\t");

        
        #line default
        #line hidden
        
        #line 59 "C:\GitHub\kallex\private\Demos\CQRS_CustomerBankAccountDemo\Abstractions\OperationABS\Operation\..\..\abscommon\CommonInclude\Common\CommonCodeblocks.ttinclude"
 
	}

	void EndBlock() {
		
        
        #line default
        #line hidden
        
        #line 63 "C:\GitHub\kallex\private\Demos\CQRS_CustomerBankAccountDemo\Abstractions\OperationABS\Operation\..\..\abscommon\CommonInclude\Common\CommonCodeblocks.ttinclude"
this.Write(" } ");

        
        #line default
        #line hidden
        
        #line 63 "C:\GitHub\kallex\private\Demos\CQRS_CustomerBankAccountDemo\Abstractions\OperationABS\Operation\..\..\abscommon\CommonInclude\Common\CommonCodeblocks.ttinclude"

	}

		
	static string RemoveScands(string sourceString) {
		return sourceString.Replace('ä', 'a').Replace('Ä', 'A').Replace('å', 'a').Replace('Å', 'A').Replace('ö', 'o').Replace('Ö', 'O');
	}
	
	public class GenerationItem
	{
		public string FileName;
		public string Content;
	}
	

        
        #line default
        #line hidden
        
        #line 1 "C:\GitHub\kallex\private\Demos\CQRS_CustomerBankAccountDemo\Abstractions\OperationABS\Operation\Operation_v1_0_namespace.ttinclude"

public class Operation_v1_0 { 
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5446
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/Operation_v1_0.xsd")]
[System.Xml.Serialization.XmlRootAttribute("OperationAbstraction", Namespace="http://tempuri.org/Operation_v1_0.xsd", IsNullable=false)]
public partial class OperationAbstractionType {
    
    private OperationsType operationsField;
    
    /// <remarks/>
    public OperationsType Operations {
        get {
            return this.operationsField;
        }
        set {
            this.operationsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/Operation_v1_0.xsd")]
public partial class OperationsType {
    
    private OperationType[] operationField;
    
    private string codeNamespaceField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Operation")]
    public OperationType[] Operation {
        get {
            return this.operationField;
        }
        set {
            this.operationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string codeNamespace {
        get {
            return this.codeNamespaceField;
        }
        set {
            this.codeNamespaceField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/Operation_v1_0.xsd")]
public partial class OperationType {
    
    private OperationSpecType operationSpecField;
    
    private ParametersType parametersField;
    
    private ExecutionType executionField;
    
    private OperationReturnValuesType operationReturnValuesField;
    
    private string nameField;
    
    /// <remarks/>
    public OperationSpecType OperationSpec {
        get {
            return this.operationSpecField;
        }
        set {
            this.operationSpecField = value;
        }
    }
    
    /// <remarks/>
    public ParametersType Parameters {
        get {
            return this.parametersField;
        }
        set {
            this.parametersField = value;
        }
    }
    
    /// <remarks/>
    public ExecutionType Execution {
        get {
            return this.executionField;
        }
        set {
            this.executionField = value;
        }
    }
    
    /// <remarks/>
    public OperationReturnValuesType OperationReturnValues {
        get {
            return this.operationReturnValuesField;
        }
        set {
            this.operationReturnValuesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/Operation_v1_0.xsd")]
public partial class OperationSpecType {
    
    private UseCaseType[] useCasesField;
    
    private RequirementType[] requirementsField;
    
    private string descriptionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("UseCase", IsNullable=false)]
    public UseCaseType[] UseCases {
        get {
            return this.useCasesField;
        }
        set {
            this.useCasesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Requirement", IsNullable=false)]
    public RequirementType[] Requirements {
        get {
            return this.requirementsField;
        }
        set {
            this.requirementsField = value;
        }
    }
    
    /// <remarks/>
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/Operation_v1_0.xsd")]
public partial class UseCaseType {
    
    private string nameField;
    
    private string locationUrlField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string locationUrl {
        get {
            return this.locationUrlField;
        }
        set {
            this.locationUrlField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/Operation_v1_0.xsd")]
public partial class OperationReturnValuesType {
    
    private VariableType[] returnValueField;
    
    private TargetType[] parameterField;
    
    private TargetType[] targetField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ReturnValue")]
    public VariableType[] ReturnValue {
        get {
            return this.returnValueField;
        }
        set {
            this.returnValueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Parameter")]
    public TargetType[] Parameter {
        get {
            return this.parameterField;
        }
        set {
            this.parameterField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Target")]
    public TargetType[] Target {
        get {
            return this.targetField;
        }
        set {
            this.targetField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/Operation_v1_0.xsd")]
public partial class VariableType {
    
    private string nameField;
    
    private string dataTypeField;
    
    private string designDescField;
    
    private VariableTypeState stateField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string dataType {
        get {
            return this.dataTypeField;
        }
        set {
            this.dataTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string designDesc {
        get {
            return this.designDescField;
        }
        set {
            this.designDescField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public VariableTypeState state {
        get {
            return this.stateField;
        }
        set {
            this.stateField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/Operation_v1_0.xsd")]
public enum VariableTypeState {
    
    /// <remarks/>
    underDesign,
    
    /// <remarks/>
    designApproved,
    
    /// <remarks/>
    implemented,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/Operation_v1_0.xsd")]
public partial class TargetType {
    
    private string nameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/Operation_v1_0.xsd")]
public partial class AdvancedExecutionType {
    
    private SequentialExecutionType[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Execution")]
    public SequentialExecutionType[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/Operation_v1_0.xsd")]
public partial class SequentialExecutionType {
    
    private object[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("MethodExecute", typeof(MethodExecuteType))]
    [System.Xml.Serialization.XmlElementAttribute("OperationExecute", typeof(OperationExecuteType))]
    [System.Xml.Serialization.XmlElementAttribute("TargetDefinition", typeof(TargetDefinitionType))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/Operation_v1_0.xsd")]
public partial class MethodExecuteType {
    
    private TargetType[] parameterField;
    
    private TargetType[] targetField;
    
    private VariableType[] returnValueField;
    
    private string nameField;
    
    private string designDescField;
    
    private VariableTypeState stateField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Parameter")]
    public TargetType[] Parameter {
        get {
            return this.parameterField;
        }
        set {
            this.parameterField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Target")]
    public TargetType[] Target {
        get {
            return this.targetField;
        }
        set {
            this.targetField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ReturnValue")]
    public VariableType[] ReturnValue {
        get {
            return this.returnValueField;
        }
        set {
            this.returnValueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string designDesc {
        get {
            return this.designDescField;
        }
        set {
            this.designDescField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public VariableTypeState state {
        get {
            return this.stateField;
        }
        set {
            this.stateField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/Operation_v1_0.xsd")]
public partial class OperationExecuteType {
    
    private TargetType[] parameterField;
    
    private TargetType[] targetField;
    
    private VariableType[] returnValueField;
    
    private string nameField;
    
    private string targetOperationNameField;
    
    private string designDescField;
    
    private VariableTypeState stateField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Parameter")]
    public TargetType[] Parameter {
        get {
            return this.parameterField;
        }
        set {
            this.parameterField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Target")]
    public TargetType[] Target {
        get {
            return this.targetField;
        }
        set {
            this.targetField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ReturnValue")]
    public VariableType[] ReturnValue {
        get {
            return this.returnValueField;
        }
        set {
            this.returnValueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string targetOperationName {
        get {
            return this.targetOperationNameField;
        }
        set {
            this.targetOperationNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string designDesc {
        get {
            return this.designDescField;
        }
        set {
            this.designDescField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public VariableTypeState state {
        get {
            return this.stateField;
        }
        set {
            this.stateField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/Operation_v1_0.xsd")]
public partial class TargetDefinitionType {
    
    private TargetType[] parameterField;
    
    private TargetType[] targetField;
    
    private string nameField;
    
    private string dataTypeField;
    
    private string designDescField;
    
    private VariableTypeState stateField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Parameter")]
    public TargetType[] Parameter {
        get {
            return this.parameterField;
        }
        set {
            this.parameterField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Target")]
    public TargetType[] Target {
        get {
            return this.targetField;
        }
        set {
            this.targetField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string dataType {
        get {
            return this.dataTypeField;
        }
        set {
            this.dataTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string designDesc {
        get {
            return this.designDescField;
        }
        set {
            this.designDescField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public VariableTypeState state {
        get {
            return this.stateField;
        }
        set {
            this.stateField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/Operation_v1_0.xsd")]
public partial class ExecutionType {
    
    private object itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("AdvancedExecution", typeof(AdvancedExecutionType))]
    [System.Xml.Serialization.XmlElementAttribute("SequentialExecution", typeof(SequentialExecutionType))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/Operation_v1_0.xsd")]
public partial class ModificationType {
    
    private TargetType[] targetField;
    
    private string nameField;
    
    private string designDescField;
    
    private VariableTypeState stateField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Target")]
    public TargetType[] Target {
        get {
            return this.targetField;
        }
        set {
            this.targetField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string designDesc {
        get {
            return this.designDescField;
        }
        set {
            this.designDescField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public VariableTypeState state {
        get {
            return this.stateField;
        }
        set {
            this.stateField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/Operation_v1_0.xsd")]
public partial class ValidationType {
    
    private TargetType[] targetField;
    
    private string nameField;
    
    private string designDescField;
    
    private VariableTypeState stateField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Target")]
    public TargetType[] Target {
        get {
            return this.targetField;
        }
        set {
            this.targetField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string designDesc {
        get {
            return this.designDescField;
        }
        set {
            this.designDescField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public VariableTypeState state {
        get {
            return this.stateField;
        }
        set {
            this.stateField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/Operation_v1_0.xsd")]
public partial class ParametersType {
    
    private VariableType[] parameterField;
    
    private object[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Parameter")]
    public VariableType[] Parameter {
        get {
            return this.parameterField;
        }
        set {
            this.parameterField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Modification", typeof(ModificationType))]
    [System.Xml.Serialization.XmlElementAttribute("Validation", typeof(ValidationType))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/Operation_v1_0.xsd")]
public partial class RequirementType {
    
    private object itemField;
    
    private string nameField;
    
    private RequirementTypeCategory categoryField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("FreeformText", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("Performance", typeof(RequirementTypePerformance))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public RequirementTypeCategory category {
        get {
            return this.categoryField;
        }
        set {
            this.categoryField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/Operation_v1_0.xsd")]
public partial class RequirementTypePerformance {
    
    private long maxMemoryBytesField;
    
    private bool maxMemoryBytesFieldSpecified;
    
    private decimal maxCPUTimeMsField;
    
    private bool maxCPUTimeMsFieldSpecified;
    
    private decimal maxTotalTimeMsField;
    
    private bool maxTotalTimeMsFieldSpecified;
    
    private long maxFileIOCountField;
    
    private bool maxFileIOCountFieldSpecified;
    
    private long maxFileIOBytesField;
    
    private bool maxFileIOBytesFieldSpecified;
    
    private decimal maxFileIOTimeMsField;
    
    private bool maxFileIOTimeMsFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public long maxMemoryBytes {
        get {
            return this.maxMemoryBytesField;
        }
        set {
            this.maxMemoryBytesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool maxMemoryBytesSpecified {
        get {
            return this.maxMemoryBytesFieldSpecified;
        }
        set {
            this.maxMemoryBytesFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal maxCPUTimeMs {
        get {
            return this.maxCPUTimeMsField;
        }
        set {
            this.maxCPUTimeMsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool maxCPUTimeMsSpecified {
        get {
            return this.maxCPUTimeMsFieldSpecified;
        }
        set {
            this.maxCPUTimeMsFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal maxTotalTimeMs {
        get {
            return this.maxTotalTimeMsField;
        }
        set {
            this.maxTotalTimeMsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool maxTotalTimeMsSpecified {
        get {
            return this.maxTotalTimeMsFieldSpecified;
        }
        set {
            this.maxTotalTimeMsFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public long maxFileIOCount {
        get {
            return this.maxFileIOCountField;
        }
        set {
            this.maxFileIOCountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool maxFileIOCountSpecified {
        get {
            return this.maxFileIOCountFieldSpecified;
        }
        set {
            this.maxFileIOCountFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public long maxFileIOBytes {
        get {
            return this.maxFileIOBytesField;
        }
        set {
            this.maxFileIOBytesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool maxFileIOBytesSpecified {
        get {
            return this.maxFileIOBytesFieldSpecified;
        }
        set {
            this.maxFileIOBytesFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal maxFileIOTimeMs {
        get {
            return this.maxFileIOTimeMsField;
        }
        set {
            this.maxFileIOTimeMsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool maxFileIOTimeMsSpecified {
        get {
            return this.maxFileIOTimeMsFieldSpecified;
        }
        set {
            this.maxFileIOTimeMsFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/Operation_v1_0.xsd")]
public enum RequirementTypeCategory {
    
    /// <remarks/>
    Customer,
    
    /// <remarks/>
    Architectural,
    
    /// <remarks/>
    Structural,
    
    /// <remarks/>
    Behavioral,
    
    /// <remarks/>
    Functional,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Non-functional")]
    Nonfunctional,
    
    /// <remarks/>
    Performance,
    
    /// <remarks/>
    Design,
    
    /// <remarks/>
    Derived,
    
    /// <remarks/>
    Allocated,
}
} 
        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "10.0.0.0")]
    public class CSharpCode_v1_0Base
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
