//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5446
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 
namespace Operation_v1_0 {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/Operation_v1_0.xsd")]
    [System.Xml.Serialization.XmlRootAttribute("OperationAbstraction", Namespace="http://tempuri.org/Operation_v1_0.xsd", IsNullable=false)]
    public partial class OperationAbstractionType {
        
        private OperationsType operationsField;
        
        /// <remarks/>
        public OperationsType Operations {
            get {
                return this.operationsField;
            }
            set {
                this.operationsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/Operation_v1_0.xsd")]
    public partial class OperationsType {
        
        private OperationType[] operationField;
        
        private string codeNamespaceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Operation")]
        public OperationType[] Operation {
            get {
                return this.operationField;
            }
            set {
                this.operationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string codeNamespace {
            get {
                return this.codeNamespaceField;
            }
            set {
                this.codeNamespaceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/Operation_v1_0.xsd")]
    public partial class OperationType {
        
        private OperationSpecType operationSpecField;
        
        private ParametersType parametersField;
        
        private ExecutionType executionField;
        
        private OperationReturnValuesType operationReturnValuesField;
        
        private string nameField;
        
        private bool isRootOperationField;
        
        public OperationType() {
            this.isRootOperationField = false;
        }
        
        /// <remarks/>
        public OperationSpecType OperationSpec {
            get {
                return this.operationSpecField;
            }
            set {
                this.operationSpecField = value;
            }
        }
        
        /// <remarks/>
        public ParametersType Parameters {
            get {
                return this.parametersField;
            }
            set {
                this.parametersField = value;
            }
        }
        
        /// <remarks/>
        public ExecutionType Execution {
            get {
                return this.executionField;
            }
            set {
                this.executionField = value;
            }
        }
        
        /// <remarks/>
        public OperationReturnValuesType OperationReturnValues {
            get {
                return this.operationReturnValuesField;
            }
            set {
                this.operationReturnValuesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool isRootOperation {
            get {
                return this.isRootOperationField;
            }
            set {
                this.isRootOperationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/Operation_v1_0.xsd")]
    public partial class OperationSpecType {
        
        private UseCaseType[] useCasesField;
        
        private RequirementType[] requirementsField;
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("UseCase", IsNullable=false)]
        public UseCaseType[] UseCases {
            get {
                return this.useCasesField;
            }
            set {
                this.useCasesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Requirement", IsNullable=false)]
        public RequirementType[] Requirements {
            get {
                return this.requirementsField;
            }
            set {
                this.requirementsField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/Operation_v1_0.xsd")]
    public partial class UseCaseType {
        
        private string nameField;
        
        private string locationUrlField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string locationUrl {
            get {
                return this.locationUrlField;
            }
            set {
                this.locationUrlField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/Operation_v1_0.xsd")]
    public partial class OperationReturnValuesType {
        
        private VariableType[] returnValueField;
        
        private TargetType[] parameterField;
        
        private TargetType[] targetField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ReturnValue")]
        public VariableType[] ReturnValue {
            get {
                return this.returnValueField;
            }
            set {
                this.returnValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Parameter")]
        public TargetType[] Parameter {
            get {
                return this.parameterField;
            }
            set {
                this.parameterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Target")]
        public TargetType[] Target {
            get {
                return this.targetField;
            }
            set {
                this.targetField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/Operation_v1_0.xsd")]
    public partial class VariableType {
        
        private string nameField;
        
        private string dataTypeField;
        
        private string designDescField;
        
        private VariableTypeState stateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string dataType {
            get {
                return this.dataTypeField;
            }
            set {
                this.dataTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string designDesc {
            get {
                return this.designDescField;
            }
            set {
                this.designDescField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public VariableTypeState state {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/Operation_v1_0.xsd")]
    public enum VariableTypeState {
        
        /// <remarks/>
        underDesign,
        
        /// <remarks/>
        designApproved,
        
        /// <remarks/>
        implemented,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/Operation_v1_0.xsd")]
    public partial class TargetType {
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/Operation_v1_0.xsd")]
    public partial class TargetDefinitionType {
        
        private TargetType[] parameterField;
        
        private TargetType[] targetField;
        
        private string nameField;
        
        private string dataTypeField;
        
        private string designDescField;
        
        private VariableTypeState stateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Parameter")]
        public TargetType[] Parameter {
            get {
                return this.parameterField;
            }
            set {
                this.parameterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Target")]
        public TargetType[] Target {
            get {
                return this.targetField;
            }
            set {
                this.targetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string dataType {
            get {
                return this.dataTypeField;
            }
            set {
                this.dataTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string designDesc {
            get {
                return this.designDescField;
            }
            set {
                this.designDescField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public VariableTypeState state {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/Operation_v1_0.xsd")]
    public partial class OperationExecuteType {
        
        private TargetType[] parameterField;
        
        private TargetType[] targetField;
        
        private VariableType[] returnValueField;
        
        private string nameField;
        
        private string targetOperationNameField;
        
        private string designDescField;
        
        private VariableTypeState stateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Parameter")]
        public TargetType[] Parameter {
            get {
                return this.parameterField;
            }
            set {
                this.parameterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Target")]
        public TargetType[] Target {
            get {
                return this.targetField;
            }
            set {
                this.targetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ReturnValue")]
        public VariableType[] ReturnValue {
            get {
                return this.returnValueField;
            }
            set {
                this.returnValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string targetOperationName {
            get {
                return this.targetOperationNameField;
            }
            set {
                this.targetOperationNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string designDesc {
            get {
                return this.designDescField;
            }
            set {
                this.designDescField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public VariableTypeState state {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/Operation_v1_0.xsd")]
    public partial class MethodExecuteType {
        
        private TargetType[] parameterField;
        
        private TargetType[] targetField;
        
        private VariableType[] returnValueField;
        
        private string nameField;
        
        private string designDescField;
        
        private VariableTypeState stateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Parameter")]
        public TargetType[] Parameter {
            get {
                return this.parameterField;
            }
            set {
                this.parameterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Target")]
        public TargetType[] Target {
            get {
                return this.targetField;
            }
            set {
                this.targetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ReturnValue")]
        public VariableType[] ReturnValue {
            get {
                return this.returnValueField;
            }
            set {
                this.returnValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string designDesc {
            get {
                return this.designDescField;
            }
            set {
                this.designDescField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public VariableTypeState state {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/Operation_v1_0.xsd")]
    public partial class ExecutionType {
        
        private object[] sequentialExecutionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("MethodExecute", typeof(MethodExecuteType), IsNullable=false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("OperationExecute", typeof(OperationExecuteType), IsNullable=false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("TargetDefinition", typeof(TargetDefinitionType), IsNullable=false)]
        public object[] SequentialExecution {
            get {
                return this.sequentialExecutionField;
            }
            set {
                this.sequentialExecutionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/Operation_v1_0.xsd")]
    public partial class ModificationType {
        
        private TargetType[] targetField;
        
        private string nameField;
        
        private string designDescField;
        
        private VariableTypeState stateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Target")]
        public TargetType[] Target {
            get {
                return this.targetField;
            }
            set {
                this.targetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string designDesc {
            get {
                return this.designDescField;
            }
            set {
                this.designDescField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public VariableTypeState state {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/Operation_v1_0.xsd")]
    public partial class ValidationType {
        
        private TargetType[] targetField;
        
        private string nameField;
        
        private string designDescField;
        
        private VariableTypeState stateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Target")]
        public TargetType[] Target {
            get {
                return this.targetField;
            }
            set {
                this.targetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string designDesc {
            get {
                return this.designDescField;
            }
            set {
                this.designDescField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public VariableTypeState state {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/Operation_v1_0.xsd")]
    public partial class ParametersType {
        
        private VariableType[] parameterField;
        
        private object[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Parameter")]
        public VariableType[] Parameter {
            get {
                return this.parameterField;
            }
            set {
                this.parameterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Modification", typeof(ModificationType))]
        [System.Xml.Serialization.XmlElementAttribute("Validation", typeof(ValidationType))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/Operation_v1_0.xsd")]
    public partial class RequirementType {
        
        private object itemField;
        
        private string nameField;
        
        private RequirementTypeCategory categoryField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FreeformText", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("Performance", typeof(RequirementTypePerformance))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public RequirementTypeCategory category {
            get {
                return this.categoryField;
            }
            set {
                this.categoryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/Operation_v1_0.xsd")]
    public partial class RequirementTypePerformance {
        
        private long maxMemoryBytesField;
        
        private bool maxMemoryBytesFieldSpecified;
        
        private decimal maxCPUTimeMsField;
        
        private bool maxCPUTimeMsFieldSpecified;
        
        private decimal maxTotalTimeMsField;
        
        private bool maxTotalTimeMsFieldSpecified;
        
        private long maxFileIOCountField;
        
        private bool maxFileIOCountFieldSpecified;
        
        private long maxFileIOBytesField;
        
        private bool maxFileIOBytesFieldSpecified;
        
        private decimal maxFileIOTimeMsField;
        
        private bool maxFileIOTimeMsFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long maxMemoryBytes {
            get {
                return this.maxMemoryBytesField;
            }
            set {
                this.maxMemoryBytesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool maxMemoryBytesSpecified {
            get {
                return this.maxMemoryBytesFieldSpecified;
            }
            set {
                this.maxMemoryBytesFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal maxCPUTimeMs {
            get {
                return this.maxCPUTimeMsField;
            }
            set {
                this.maxCPUTimeMsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool maxCPUTimeMsSpecified {
            get {
                return this.maxCPUTimeMsFieldSpecified;
            }
            set {
                this.maxCPUTimeMsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal maxTotalTimeMs {
            get {
                return this.maxTotalTimeMsField;
            }
            set {
                this.maxTotalTimeMsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool maxTotalTimeMsSpecified {
            get {
                return this.maxTotalTimeMsFieldSpecified;
            }
            set {
                this.maxTotalTimeMsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long maxFileIOCount {
            get {
                return this.maxFileIOCountField;
            }
            set {
                this.maxFileIOCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool maxFileIOCountSpecified {
            get {
                return this.maxFileIOCountFieldSpecified;
            }
            set {
                this.maxFileIOCountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long maxFileIOBytes {
            get {
                return this.maxFileIOBytesField;
            }
            set {
                this.maxFileIOBytesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool maxFileIOBytesSpecified {
            get {
                return this.maxFileIOBytesFieldSpecified;
            }
            set {
                this.maxFileIOBytesFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal maxFileIOTimeMs {
            get {
                return this.maxFileIOTimeMsField;
            }
            set {
                this.maxFileIOTimeMsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool maxFileIOTimeMsSpecified {
            get {
                return this.maxFileIOTimeMsFieldSpecified;
            }
            set {
                this.maxFileIOTimeMsFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/Operation_v1_0.xsd")]
    public enum RequirementTypeCategory {
        
        /// <remarks/>
        Customer,
        
        /// <remarks/>
        Architectural,
        
        /// <remarks/>
        Structural,
        
        /// <remarks/>
        Behavioral,
        
        /// <remarks/>
        Functional,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Non-functional")]
        Nonfunctional,
        
        /// <remarks/>
        Performance,
        
        /// <remarks/>
        Design,
        
        /// <remarks/>
        Derived,
        
        /// <remarks/>
        Allocated,
    }
}
